version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hakimfrh/Whatsapp-bot-Jawir:latest
    volumes:
      - data:/app/data
    environment:
      - NODE_ENV=production
      # Add additional environment variables if needed

volumes:
  data:
