name: Whatsapp-Bot-Jawir
image: dockerhubusername/myapp:latest # Replace with your Docker image name

# Define your application's services
services:
  app:
    build: .
    # Add additional services if needed

# Define your application's volumes
volumes:
  - name: data
    mountPath: /app/data # Replace with your desired mount path

# Define your application's environment variables
environment:
  - NODE_ENV=production
  # Add additional environment variables if needed

# Define any additional configurations, like ports, commands, etc.
# See the Okteto documentation for available options
